[package]
name = "safehide-api"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
futures-util = "0.3.31"
mongodb = "3.5.0"
dotenv = "0.15.0"
regex = "1.12.2"
chrono = { version = "0.4.43", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }